[project]
name = "back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gr Didalin", email = "rewsbar@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "maxapi>=1.2.2",
    "numpy>=2.5.3",
    "passlib>=1.7.4",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.0",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy[asyncio]>=2.0.54",
    "uvicorn[standard]>=0.53.0",
]


[project.scripts]
back = "back:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
